### ISSUE TITLE
links should be .md instead of .html

### ISSUE THREAD

**Issue by extreme4all** [Khan/kotlin-for-python-developers#11]

**Comment by aasmundeldhuset** [comment]
I assume you were referring to the numbered `.md` files? Those existed for the purpose of powering a now-defunct mirror at kotlinlang.org, where the pages were served with an `.html` suffix; they were generated from `README.md` with a script that among other things converted the links. I looked through all `html` links in `README.md`, and they are all to external sites. All doc-internal links are in the form of `#`-based anchor references. However, this did prompt me to check all the external links in `README.md`, and I found several that needed to be updated (3d2eacbd803986167f7a4e94dfa4eb52373916c8) - thanks! I'll close this issue, but please let me know if I misunderstood what you were referring to.

(Sorry about the extremely late reply - due to the pandemic, my mental bandwidth has been very limited.)
