### ISSUE TITLE
I hope split.py has a version that works under python3

### ISSUE THREAD

**Issue by Yue-plus** [Khan/kotlin-for-python-developers#8]
I hope `split.py` has a version that works under `python3`.

**Comment by aasmundeldhuset** [comment]
`split.py` and the numbered `.md` files it generated existed for the purpose of powering a mirror at kotlinlang.org. They stopped hosting the mirror recently, so the script is no longer needed, and I deleted it in 4b9f02bc34cc632e10951da3882118fc43511000. If you would like to contribute any edits, it is now sufficient to edit `README.md`.

(Sorry about the extremely late reply - due to the pandemic, my mental bandwidth has been very limited.)
